language: objective-c,Swift
osx_image: xcode10.1
xcode_project: openxc-ios-framework.xcodeproj
xcode_scheme: openxc-ios-framework
xcode_sdk: iphonesimulator11.0

branches:
- master
- next

script:
- xcodebuild clean build test -project openxc-ios-framework.xcodeproj -scheme openxc-ios-framework -destination 'platform=iOS Simulator,name=iPhone 6s,OS=9.2'  ONLY_ACTIVE_ARCH=NO
